"""Orchestrator state schema for LangGraph.

Uses Annotated types with reducers per LangGraph 1.2.x best practices.
List fields use operator.add for append semantics (accumulate across retries).
Scalar fields use last-write-wins (overwritten each pass).

Design rules:
- Never mutate state in-place inside nodes.
- Nodes return partial dicts with only the keys they update.
- operator.add fields accumulate across retries and execution steps.
- Scalar fields are overwritten each evaluation pass.
"""

import operator
from typing import Annotated, TypedDict


class OrchestratorState(TypedDict, total=False):
    """Complete state for the remediation orchestration workflow.

    This TypedDict flows through every node in the LangGraph.
    Each node reads what it needs and returns a partial update dict.
    """

    # --- Input ---
    incident: dict  # Serialized Incident

    # --- Service Identification ---
    service_name: str

    # --- RAG (append-only: multiple retrieval rounds accumulate) ---
    retrieved_documents: Annotated[list, operator.add]

    # --- Contract (deterministic lookup: last-write-wins) ---
    retrieved_contract: dict  # Serialized OperationalContract

    # --- Planning ---
    proposed_plan: dict  # Serialized RemediationPlan
    normalized_actions: list[dict]  # Serialized list of NormalizedAction

    # --- Guardrails (overwritten each evaluation pass) ---
    guardrail_status: str  # "APPROVED" | "REJECTED"
    violations: list[str]

    # --- Retry (explicitly incremented in retry node) ---
    retry_count: int

    # --- Risk ---
    risk_level: str  # "LOW" | "MEDIUM" | "HIGH" | "CRITICAL"
    approval_required: bool

    # --- Human (set by interrupt resume) ---
    human_decision: str  # "APPROVED" | "REJECTED"
    approved_by: str  # identity of the approver/rejecter

    # --- Execution (append-only: accumulates across multi-step execution) ---
    execution_history: Annotated[list, operator.add]

    # --- Compensation (append-only: saga rollback actions run on failure) ---
    compensation_history: Annotated[list, operator.add]

    # --- Postconditions (overwritten after each validation pass) ---
    postcondition_results: list[dict]

    # --- Final ---
    final_status: str  # "SUCCESS" | "FAILED" | "ESCALATED" | "DENIED"

    # --- Post-incident summary (generated by SummaryAgent in finalize) ---
    executive_summary: str

    # --- Audit (append-only: full trail) ---
    audit_trail: Annotated[list, operator.add]
